### PR TITLE
Added undo with 'z' key

### PR DESCRIPTION
**Pull request by akumm2k**
Undoing the simulations helped me understand and improve my strategies better, besides helping me debug when needed. I figured this can be a good addition to the program.

The moves in the simulation can be undone by pressing the 'q' key and redone by pressing the space bar.

### CODE REVIEW

**Comment by medovina** [comment]
Thanks for this pull request - this could be a nice change.

- I'd prefer the shortcut 'z' rather than 'q', since it is more like ctrl+Z which is the usual shortcut for undoing.

- The boolean 'undoneCapture' is set but never read, so it's unnecessary.

- With this change, undoing doesn't work properly in an interactive game where a person is playing versus the computer.  You should either fix that, or disable undoing when the game is interactive.

- The field name 'stk' is a bit cryptic.  'stack' would be a better name.

- A MoveCapture is just a pair of a Move and a bool, so I'd just use a pair of type (Move, bool) instead.

**Comment by medovina** [comment]
A couple more points:

- In your change, please update the README with documentation for this feature.

- The usual convention for git commit messages is to use the imperative mood in the subject line:

   https://chris.beams.io/posts/git-commit/#imperative

So really your subject line should be "__Add__ undo with 'q' key".  There's no need to amend your previous commit now, but please keep this in mind for the future.

**Comment by akumm2k** [comment]
I have made the following changes:
- Change the undo shortcut from 'q' to 'z'
- Remove boolean 'undoneCapture'
- Enable undoing only for simulations
- Change field name from 'stk' to 'undoStack'
- Use (Move, bool) pair instead of MoveCapture class
- Update README 

Should I also edit the title of this pull request?

**Comment by medovina** [comment]
Thanks for the update.  I edited the pull request title.

In several places in OnDrawn(), you have the expression

```
undoable() || !undone
```

Instead, you could just write

```
!undone
```

since the first expression is true if and only if (!undone) is true.  That means that the function undoable() is unnecessary.

**Comment by akumm2k** [comment]
Thank you for pointing this out! I had a different logical expression in undoable() before, and I forgot to remove it in the last version.
I have removed undoable() in my last commit.

**Comment by medovina** [comment]
Thanks for the update.

- If I run `dotnet run -- -seed 0` to view the game with seed 0, undo doesn't work during the simulation.
- In unmove(), instead of
```
                var oldMove = undoStack.Pop();
                Move undoMove = oldMove.Item1;
                bool undoCapture = oldMove.Item2;
```

you could just write

```
                (Move undoMove, bool undoCapture) = undoStack.Pop();
```

- In the line
```
                if (lastMove != null && (!undone) && wasCapture &&
```

  the parentheses around !undone are unnecessary.

**Pull request merged**
